spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://camundadb:5432/camunda
    username: camunda
    password: camunda
  application:
    name: task-management
camunda:
  bpm:
    database:
      type: postgres
    enabled: true
    history-level: full
    id-generator: strong
